// Shared types for the application

export interface StorySection {
  id: number;
  sectionName: string; // e.g., "storyname_section_1"
  sceneDescription: string; // What happens in this scene
  script: string; // Direct text from the story for this section
  duration?: number;
  status: 'pending' | 'generating' | 'completed' | 'failed';
  error?: string;
  
  // File paths (populated during generation)
  scriptPath?: string; // Path to the script file for this section
  narrationScriptPath?: string; // Path to the narration script file for this section (generated by audio service)
  videoPath?: string; // Path to the video file for this section
  audioPath?: string; // Path to the audio file for this section
  backgroundImagePath?: string; // Path to the background image for this section
}

// Keep the old interface for backward compatibility
export interface StorySegment extends StorySection {}

export interface StoryStyle {
  characters: Array<{
    name: string;
    description: string;
    physicalTraits: string;
  }>;
  setting: {
    location: string;
    timeperiod: string;
    atmosphere: string;
  };
  visualStyle: {
    artStyle: string;
    colorPalette: string;
    cinematography: string;
  };
}

export interface StoryData {
  id: string;
  storyName: string; // Clean name for folder creation
  originalFilename: string;
  uploadedAt: string;
  status: 'uploaded' | 'analyzing' | 'extracting_style' | 'generating_reference_image' | 'generating_sections' | 'generating_videos' | 'completed' | 'failed';
  progress: number;
  currentStep?: string;
  textContent?: string;
  styleInfo?: StoryStyle;
  referenceImagePath?: string;
  referenceImageUrl?: string;
  sections: StorySection[];
  error?: string;
  
  // Legacy support
  segments: StorySegment[];
}

export interface UploadResponse {
  success: boolean;
  storyId: string;
  message: string;
}

export interface ProcessingStatus {
  storyId: string;
  status: StoryData['status'];
  progress: number;
  currentStep?: string;
  sections?: StorySection[];
  styleInfo?: StoryStyle;
  error?: string;
  
  // Legacy support
  segments?: StorySegment[];
}


export interface GeminiVeoRequest {
  prompt: string; // The prompt to generate the video
  duration?: number; // The duration of the video
  aspectRatio?: '16:9' | '9:16'; // The aspect ratio of the video
  resolution?: '720p' | '1080p';
  negativePrompt?: string; // the negative prompt to avoid
  personGeneration?: 'allow_adult' | 'disallow';
  seed?: number; // the seed for the video
  sampleCount?: number; // the number of samples to generate
  /** Optional image-to-video seed frame. Provide one of uri or imageBytes+mimeType. */
  image?: {
    uri?: string;              // e.g., https://...
    imageBytes?: string;       // base64-encoded image
    mimeType?: string;         // e.g., 'image/png', required if imageBytes is set
  };
  model?: 'veo-3.0-generate-001' | 'veo-3.0-fast-generate-001'; // the model to use
}

export interface GeminiVeoResponse {
  success: boolean;
  videoUrl?: string;
  videoPath?: string;
  error?: string;
}

export interface ApiError {
  error: string;
  message: string;
  statusCode: number;
}

